[project]
name = "helmet-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zainulabidinrubani", email = "fiverrzain03@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "opencv-python<5",
    "tensorflow>=2.21.0",
    "tensorflow-keras>=0.1",
    "ultralytics>=8.4.138",
]

[project.scripts]
helmet-detection = "helmet_detection:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
